[project]
name = "pony-turnarounds"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ego-lay_atman-bay", email = "70973578+ego-lay-atman-bay@users.noreply.github.com" }
]
requires-python = "==3.13.*"
dependencies = [
    "bpy>=5.1",
    "discord-py>=2.7.1",
    "luna-kit[rk,xml]",
    "pillow>=12.3.0",
]

[project.scripts]
pony-turnarounds = "pony_turnarounds:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
luna-kit = { git = "https://github.com/ego-lay-atman-bay/luna-kit/" }
